apiVersion: v1
kind: PersistentVolume
metadata:
  name: senact-pv
  labels:
    type: local
spec:
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "~/PycharmProjects/test1"
    type: DirectoryOrCreate
