kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: senact-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
    limits:
      storage: 100Mi
